---
- name: Debug operation
  debug:
    var: zabbix_operation

- name: Include install operations
  ansible.builtin.include_tasks: install.yml
  when: zabbix_operation == "install"

- name: Include install operations
  ansible.builtin.include_tasks: remove.yml
  when: zabbix_operation == "remove"

...
